name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# required for upload
permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run format check
        run: make format-check
              
      - name: Continuous Integration
        run: make ci
