name: WEB

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: 

defaults:
  run:
    shell: bash

# required for upload
permissions:
  contents: write

jobs:

  emsdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-gfx-dev build-essential cmake make

      - name: Set up Emscripten
        run: |
          sudo apt update -y
          sudo apt install -y build-essential clang python3 cmake git

          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk

          ./emsdk install latest
          ./emsdk activate latest

      - name: Build WebAssembly
        run: |
          source ./emsdk/emsdk_env.sh
          make clean build-wasm

        # Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build